/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package localchat

import org.scalatest.funsuite.AnyFunSuite
import org.junit.runner.RunWith
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class MyAppSuite extends AnyFunSuite {
  test("App has a greeting") {
    assert(MyApp.greeting() != null)
  }
}
